import { configDefaults, defineConfig } from "vitest/config";
import { fileURLToPath } from "node:url";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL(".", import.meta.url)),
    },
  },
  test: {
    exclude: [
      ...configDefaults.exclude,
      "e2e/**",
      "playwright-report/**",
      "test-results/**",
    ],
    coverage: {
      provider: "v8",
      include: [
        "lib/account-erasure.ts",
        "lib/account-erasure-checkpoint.ts",
        "lib/evidence-operation-journal.ts",
        "lib/historical-snapshots.ts",
        "lib/persistence.ts",
        "lib/portable-workspace-archive.ts",
        "lib/provider-cloud-reconciliation.ts",
        "lib/provider-cloud-save.ts",
        "lib/provider-domain-commands.ts",
        "lib/provider-evidence.ts",
        "lib/provider-goal-evidence.ts",
        "lib/provider-local-bootstrap.ts",
        "lib/provider-portable-archive.ts",
        "lib/provider-remote-evidence-cleanup.ts",
        "lib/provider-state.ts",
        "lib/provider-workspace-replacement.ts",
        "lib/review-metric-movements.ts",
        "lib/state-migrations.ts",
        "lib/state-schema.ts",
        "lib/sync-reconciliation.ts",
        "lib/utils.ts",
        "lib/workspace-capacity.ts",
        "lib/workspace-merge.ts",
      ],
      thresholds: {
        statements: 70,
        branches: 70,
        functions: 75,
        lines: 75,
        "lib/account-erasure-checkpoint.ts": {
          statements: 84,
          branches: 85,
          functions: 95,
          lines: 84,
        },
        "lib/account-erasure.ts": {
          statements: 75,
          branches: 68,
          functions: 72,
          lines: 80,
        },
        "lib/evidence-operation-journal.ts": {
          statements: 85,
          branches: 70,
          functions: 95,
          lines: 85,
        },
        "lib/historical-snapshots.ts": {
          statements: 80,
          branches: 50,
          functions: 80,
          lines: 82,
        },
        "lib/persistence.ts": {
          statements: 30,
          branches: 45,
          functions: 30,
          lines: 30,
        },
        "lib/portable-workspace-archive.ts": {
          statements: 80,
          branches: 68,
          functions: 95,
          lines: 80,
        },
        "lib/provider-cloud-reconciliation.ts": {
          statements: 78,
          branches: 75,
          functions: 95,
          lines: 82,
        },
        "lib/provider-cloud-save.ts": {
          statements: 92,
          branches: 90,
          functions: 95,
          lines: 92,
        },
        "lib/provider-evidence.ts": {
          statements: 90,
          branches: 80,
          functions: 95,
          lines: 90,
        },
        "lib/provider-goal-evidence.ts": {
          statements: 85,
          branches: 72,
          functions: 95,
          lines: 85,
        },
        "lib/provider-local-bootstrap.ts": {
          statements: 88,
          branches: 72,
          functions: 95,
          lines: 88,
        },
        "lib/provider-portable-archive.ts": {
          statements: 92,
          branches: 78,
          functions: 95,
          lines: 92,
        },
        "lib/provider-remote-evidence-cleanup.ts": {
          statements: 95,
          branches: 95,
          functions: 95,
          lines: 95,
        },
        "lib/provider-state.ts": {
          statements: 88,
          branches: 85,
          functions: 90,
          lines: 90,
        },
        "lib/provider-workspace-replacement.ts": {
          statements: 95,
          branches: 95,
          functions: 95,
          lines: 95,
        },
        "lib/review-metric-movements.ts": {
          statements: 95,
          branches: 68,
          functions: 95,
          lines: 95,
        },
        "lib/state-migrations.ts": {
          statements: 85,
          branches: 78,
          functions: 94,
          lines: 86,
        },
        "lib/state-schema.ts": {
          statements: 85,
          branches: 78,
          functions: 90,
          lines: 88,
        },
        "lib/sync-reconciliation.ts": {
          statements: 95,
          branches: 95,
          functions: 90,
          lines: 95,
        },
        "lib/utils.ts": {
          statements: 82,
          branches: 82,
          functions: 78,
          lines: 85,
        },
        "lib/workspace-capacity.ts": {
          statements: 82,
          branches: 84,
          functions: 95,
          lines: 82,
        },
        "lib/workspace-merge.ts": {
          statements: 92,
          branches: 70,
          functions: 95,
          lines: 94,
        },
      },
    },
  },
});
